DROP TABLE IF EXISTS request_detail CASCADE;
DROP TABLE IF EXISTS request_header CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS department CASCADE;