
DROP TABLE IF EXISTS RequestDetail CASCADE;
DROP TABLE IF EXISTS RequestHeader CASCADE;
DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Supplier CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Department CASCADE;